/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-1",
    "aws_appsync_graphqlEndpoint": "https://kemepxma5bbenb2l6qwozqknsa.appsync-api.ap-northeast-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-northeast-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-zamb56vn7jct3n7y2ydsbpcppy",
    "aws_cognito_identity_pool_id": "ap-northeast-1:1bf58702-55f8-46ae-a11c-d40390c1c146",
    "aws_cognito_region": "ap-northeast-1",
    "aws_user_pools_id": "ap-northeast-1_nPVXMqVUQ",
    "aws_user_pools_web_client_id": "5513fucsbq30teref4i3amaoh2",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_content_delivery_bucket": "roulettappforuser-20220831070103-hostingbucket-develop",
    "aws_content_delivery_bucket_region": "ap-northeast-1",
    "aws_content_delivery_url": "http://roulettappforuser-20220831070103-hostingbucket-develop.s3-website-ap-northeast-1.amazonaws.com",
    "Auth": {
        "region": "ap-northeast-1",
        "userPoolId": "ap-northeast-1_0Krv1RazL",
        "userPoolWebClientId": "4pt1ocnnrfbsdfe2j1j5uro5a8",
        "oauth": {
            "domain": "https://cloud8-g.auth.ap-northeast-1.amazoncognito.com",
            "scope": [
                "openid"
            ],
            "redirectSignIn": "https://localhost:3000/",
            "redirectSignOut": "https://localhost:3000/",
            "responseType": "code"
        }
    },
    "API": {
        "GraphQL": {
            "endpoint": "https://kemepxma5bbenb2l6qwozqknsa.appsync-api.ap-northeast-1.amazonaws.com/graphql",
            "region": "ap-northeast-1",
            "defaultAuthMode": "apiKey",
            "apiKey": "da2-lckq6nki2rdf5bat6hejkeqmaq"
        }
    }
};


export default awsmobile;
